# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.kcountDNA <- function(x, k = 5L) {
    .Call('_kmer_kcountDNA', PACKAGE = 'kmer', x, k)
}

.kdist <- function(x, from, to, seqlengths, k) {
    .Call('_kmer_kdist', PACKAGE = 'kmer', x, from, to, seqlengths, k)
}

